{
 "title": "Order Processor Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Order Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(order_processing_count[5m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Data Generation Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(data_generator_customer_total[1m]))",
     "legendFormat": "Customers"
    },
    {
     "expr": "sum(increase(data_generator_order_total[1m]))",
     "legendFormat": "Orders"
    },
    {
     "expr": "sum(increase(data_generator_document_total[1m]))",
     "legendFormat": "Documents"
    },
    {
     "expr": "sum(increase(data_generator_communication_total[1m]))",
     "legendFormat": "Communications"
    }
   ]
  },
  {
   "title": "Total Generated Data",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(data_generator_customer_total) by (instance)",
     "legendFormat": "Customers"
    },
    {
     "expr": "sum(data_generator_order_total) by (instance)",
     "legendFormat": "Orders"
    },
    {
     "expr": "sum(data_generator_document_total) by (instance)",
     "legendFormat": "Documents"
    },
    {
     "expr": "sum(data_generator_communication_total) by (instance)",
     "legendFormat": "Communications"
    }
   ]
  }
 ]
}